language: node_js
node_js: "stable"
sudo: required
cache: yarn
script:
  - yarn test --no-watch
  - yarn build
# Or use SemanticRelease instead of this
# https://docs.travis-ci.com/user/deployment/releases/ Deploy to github releases
# deploy:
#   provider: releases
#   api_key: "GITHUB OAUTH TOKEN"
#   file: "FILE TO UPLOAD"
#   skip_cleanup: true
#   draft: true # Lets you make draft releases and not real ones
#   on:
#     tags: true
